Two cupid_webpage fixes
1. Depending on how your environment is configured, you either need to import
util or cupid.util (and git_helper or cupid.git_helper); added try / except
blocks for both imports
2. Don't update github_pages_dir to a realpath unless it is non-empty (want to
keep default behavior of not doing anything if user doesn't specify -g option;
I was getting

RuntimeError: When specifying -g/--github-pages-dir, you must also provide -n/--name

even when not specifying -g)