CUPiDScriptRunner uses conda run -n ...
First pass at trying to use conda run instead of the typical python
interpreter. Somewhat successful:

ploomber.exceptions.TaskBuildError: Error building task 'divergence': the task ran successfully but the product File('vector.png') is missing. Ensure your code is generating it.
ploomber.exceptions.TaskBuildError: Exception when running on_finish for task 'divergence'